version: "2"
run:
  go: "1.24"
  issues-exit-code: 1
  tests: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: false
    checkstyle:
      path: report.xml
linters:
  enable:
    - depguard
    - dogsled
    - dupl
    - gocognit
    - goconst
    - gocyclo
    - gosec
    - lll
    - misspell
    - testpackage
    - unconvert
    - unparam
  disable:
    - asciicheck
    - bodyclose
    - err113
    - exhaustive
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - goheader
    - goprintffuncname
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/
            - go.opentelemetry.io/
            - go.uber.org/
    errcheck:
      check-type-assertions: true
    gocognit:
      min-complexity: 30
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 200
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test\.go
    paths:
      - ^*doc.go
      - ^*mockup.go
      - config
      - .idea
      - .vscode
      - docs
      - tools
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - ^*doc.go
      - ^*mockup.go
      - config
      - .idea
      - .vscode
      - docs
      - tools
